# Project supplied default configuration.  Add a new configuration file 'config.yml' where you can overwrite any settings depicted below.
# config.yml is not tracked by the version management system, while config.default.yml is.
confluence_space_name: "ATC" # SPACE KEY. GO TO: SPACE TOOLS -> Overview -> Space Details -> Key
confluence_space_home_page_name: 'ATC Home' # SPACE HOME. GO TO: SPACE TOOLS -> Overview -> Space Details -> Home page
confluence_name_of_root_directory: 'Atomic Threat Coverage'
md_name_of_root_directory: 'Atomic_Threat_Coverage'
confluence_rest_api_url: 'https://atomicthreatcoverage.atlassian.net/wiki/rest/api/'
# to get sample viewpage url go to 'Page Information' for any page from your confluence
# you will be redirected to sth like https://atomicthreatcoverage.atlassian.net/wiki/pages/viewinfo.action?pageId=115606439
# change viewinfo to viewpage and delete number from the end
# you should get sth like https://atomicthreatcoverage.atlassian.net/wiki/pages/viewpage.action?pageId=
confluence_viewpage_url: 'https://atomicthreatcoverage.atlassian.net/wiki/pages/viewpage.action?pageId='
detection_rules_directories:
  - 'detection_rules/sigma/rules/windows/builtin'
  - 'detection_rules/sigma/rules/windows/malware'
  - 'detection_rules/sigma/rules/windows/other'
  - 'detection_rules/sigma/rules/windows/powershell'
  - 'detection_rules/sigma/rules/windows/process_creation'
  - 'detection_rules/sigma/rules/windows/sysmon'
triggers_directory: 'triggers/atomic-red-team/atomics'
templates_directory: 'scripts/templates'
mitigation_systems_directory: 'mitigation/atc-mitigation/mitigation_systems'
mitigation_policies_directory: 'mitigation/atc-mitigation/mitigation_policies'
hardening_policies_directory: 'mitigation/atc-mitigation/hardening_policies'
exported_analytics_directory: 'analytics/generated'
# Sigma part, this should be configured according to needs, used mapping
sigmac_path: 'detection_rules/sigma/tools/sigmac'
detection_queries: 'powershell,es-qs,xpack-watcher,graylog,splunk,logpoint,grep'
powershell_sigma_config: 'detection_rules/sigma/tools/config/powershell.yml'
es-qs_sigma_config: 'detection_rules/sigma/tools/config/winlogbeat.yml'
xpack-watcher_sigma_config: 'detection_rules/sigma/tools/config/winlogbeat.yml'
splunk_sigma_config: 'detection_rules/sigma/tools/config/splunk-windows.yml'
logpoint_sigma_config: 'detection_rules/sigma/tools/config/logpoint-windows.yml'
customers_directory: 'customers'
usecases_directory: 'use_cases'
##
## DATA PART
##
logging_policies_dir: 'data/atc_data/logging_policies'
data_needed_dir: 'data/atc_data/data_needed'
enrichments_dir: 'data/atc_data/enrichments'
##
## RE&CT PART
##
response_playbooks_dir: 'response/atc_react/response_playbooks/'
response_actions_dir: 'response/atc_react/response_actions'
response_stages_dir: 'response/atc_react/response_stages'
thehive_templates_dir: 'analytics/generated/thehive_templates'
react_web_kb_base_url: 'https://atc-project.github.io/atc-react/'
rs_summary_dir: 'Atomic_Threat_Coverage/Response_Stages'
##
## Mappings part
##
# RE&CT
remote_react_json_url: 'https://raw.githubusercontent.com//atc-project/atc-react/master/docs/react.json'
local_react_json_url: 'response/atc_react/docs/react.json'
react_mapping_url: 'response/atc_react/scripts/react_mapping.py'
# ATT&CK
attack_json_url: 'https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json'
attack_mapping_url: 'scripts/attack_mapping.py'
# AMITT
amitt_json_url: 'https://raw.githubusercontent.com/cogsec-collaborative/amitt_cti/master/amitt/amitt-attack.json'
amitt_mapping_url: 'scripts/amitt_mapping.py'
